#!/bin/bash

#
apt update

#ssh
apt install -y openssh-server
systemctl enable ssh

#
apt install -y mc tmux git x11vnc python3 net-tools

#openvpn
apt install -y openvpn
systemctl enable openvpn@client

#nvidia driver
apt install -y nvidia-driver-390