#!/bin/bash

/home/user/miner/claymore/ethdcrminer64 -epool us1.ethpool.org:3333 -ewal 0x892070E6B885F1B32b0405C91ba68309e769F6Ea.1060 -epsw x -tt -85 -ttli 70 -tstop -83 -r 360

#-dpool stratum+tcp://dcr.suprnova.cc:3252 -dwal Redhex.my -dpsw x