#!/bin/sh

#nvidia-settings --query all

#nvidia-settings -a [gpu:0]/GPUOverclockingState=1
#nvidia-settings -a [gpu:0]/GPU2DClockFreqs=350,550
#nvidia-settings -a [gpu:0]/GPU3DClockFreqs=500,800

#fan control
nvidia-settings -a [gpu:0]/GPUFanControlState=1
nvidia-settings -a [fan:0]/GPUTargetFanSpeed=70

#-200MHz 1200Mhz
nvidia-settings -a [gpu:0]/GPUGraphicsClockOffset[3]=-200

#-2000MHz 2000Mhz
nvidia-settings -a [gpu:0]/GPUMemoryTransferRateOffset[3]=1950

nvidia-smi